

## PUT YOUR INFORMATION AS USERNAME, CHANNEL AND THE INCOMMING WEBHOOK

route:
   receiver: 'slack'

receivers:
   - name: 'slack'
     slack_configs:
        - send_resolved: true
          username: 'joaodore'
          channel: '#monitoração'
          api_url: 'https://hooks.slack.com/services/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'
